/**
 * Handoff CMS API Route
 * Auto-generated by `handoff init`.
 *
 * GET /api/handoff — returns all content
 * PUT /api/handoff — updates content and revalidates pages
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'
import { NextRequest, NextResponse } from 'next/server'
import { revalidatePath } from 'next/cache'

const CONTENT_PATH = join(process.cwd(), 'handoff', 'content.json')

function readContent(): Record<string, any> {
  try {
    return JSON.parse(readFileSync(CONTENT_PATH, 'utf-8'))
  } catch {
    return {}
  }
}

function writeContent(content: Record<string, any>) {
  mkdirSync(join(process.cwd(), 'handoff'), { recursive: true })
  writeFileSync(CONTENT_PATH, JSON.stringify(content, null, 2))
}

export async function GET() {
  const content = readContent()
  return NextResponse.json(content)
}

export async function PUT(request: NextRequest) {
  try {
    const body = await request.json()
    const current = readContent()

    // Merge updates
    const updated = { ...current, ...body }
    writeContent(updated)

    // Revalidate all pages
    revalidatePath('/', 'layout')

    return NextResponse.json({ success: true, content: updated })
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to update content' },
      { status: 500 }
    )
  }
}
