/**
 * Handoff CMS Components
 * Auto-generated by `handoff init`. You can edit this file.
 *
 * These are React Server Components that read content from handoff/content.json.
 * In production, they fall back to their children if the content file is missing.
 */
import { readFileSync } from 'fs'
import { join } from 'path'

// Read content from JSON file (server-side only)
function getContent(): Record<string, any> {
  try {
    const raw = readFileSync(join(process.cwd(), 'handoff', 'content.json'), 'utf-8')
    return JSON.parse(raw)
  } catch {
    return {}
  }
}

interface EditableProps {
  field: string
  tag?: string
  children?: React.ReactNode
  [key: string]: any
}

/**
 * Editable text component.
 * Reads content from the Handoff content store.
 * Falls back to children (original hardcoded text) if no CMS content exists.
 */
export function Editable({ field, tag, children, ...props }: EditableProps) {
  const content = getContent()
  const value = content[field]
  const Tag = (tag || 'span') as any

  return <Tag {...props}>{value ?? children}</Tag>
}

interface EditableImageProps {
  field: string
  src: string
  alt?: string
  [key: string]: any
}

/**
 * Editable image component.
 * Reads image src/alt from the Handoff content store.
 * Falls back to original src/alt if no CMS content exists.
 */
export function EditableImage({ field, src, alt, ...props }: EditableImageProps) {
  const content = getContent()
  const imageData = content[field]

  const resolvedSrc = imageData?.src ?? src
  const resolvedAlt = imageData?.alt ?? alt ?? ''

  // eslint-disable-next-line @next/next/no-img-element
  return <img src={resolvedSrc} alt={resolvedAlt} {...props} />
}
