'use client'

/**
 * Handoff CMS Editor
 * Auto-generated by `handoff init`.
 *
 * A simple content editor at /handoff.
 * Edit text fields and see changes on your live site.
 */
import { useState, useEffect } from 'react'

export default function HandoffEditor() {
  const [content, setContent] = useState<Record<string, any>>({})
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetch('/api/handoff')
      .then(r => r.json())
      .then(data => {
        setContent(data)
        setLoading(false)
      })
      .catch(() => setLoading(false))
  }, [])

  const handleChange = (key: string, value: string) => {
    setContent(prev => ({ ...prev, [key]: value }))
    setSaved(false)
  }

  const handleImageChange = (key: string, field: 'src' | 'alt', value: string) => {
    setContent(prev => ({
      ...prev,
      [key]: { ...((prev[key] as any) || {}), [field]: value },
    }))
    setSaved(false)
  }

  const handleSave = async () => {
    setSaving(true)
    try {
      await fetch('/api/handoff', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(content),
      })
      setSaved(true)
    } catch (e) {
      alert('Failed to save. Check the console.')
      console.error(e)
    }
    setSaving(false)
  }

  if (loading) {
    return (
      <div style={styles.container}>
        <div style={styles.header}>
          <h1 style={styles.title}>Handoff CMS</h1>
        </div>
        <p style={{ textAlign: 'center', padding: '40px', color: '#666' }}>Loading content...</p>
      </div>
    )
  }

  // Group fields by section
  const sections: Record<string, { key: string; value: any }[]> = {}
  for (const [key, value] of Object.entries(content)) {
    const [section] = key.split('.')
    if (!sections[section]) sections[section] = []
    sections[section].push({ key, value })
  }

  return (
    <div style={styles.container}>
      <div style={styles.header}>
        <div>
          <h1 style={styles.title}>Handoff CMS</h1>
          <p style={styles.subtitle}>Edit your site content below. Changes appear after saving.</p>
        </div>
        <button
          onClick={handleSave}
          disabled={saving || saved}
          style={{
            ...styles.saveButton,
            opacity: saving || saved ? 0.6 : 1,
            background: saved ? '#22c55e' : '#0070f3',
          }}
        >
          {saving ? 'Saving...' : saved ? '✓ Saved' : 'Save & Publish'}
        </button>
      </div>

      {Object.entries(sections).map(([sectionName, fields]) => (
        <div key={sectionName} style={styles.section}>
          <h2 style={styles.sectionTitle}>{sectionName}</h2>
          {fields.map(({ key, value }) => {
            const fieldName = key.split('.').slice(1).join('.')
            const isImage = typeof value === 'object' && value !== null && 'src' in value

            if (isImage) {
              return (
                <div key={key} style={styles.field}>
                  <label style={styles.label}>
                    {fieldName}
                    <span style={styles.badge}>image</span>
                  </label>
                  {value.src && (
                    <img
                      src={value.src}
                      alt={value.alt || ''}
                      style={{ maxWidth: '200px', borderRadius: '8px', marginBottom: '8px' }}
                    />
                  )}
                  <input
                    style={styles.input}
                    value={value.src || ''}
                    onChange={e => handleImageChange(key, 'src', e.target.value)}
                    placeholder="Image URL"
                  />
                  <input
                    style={{ ...styles.input, marginTop: '4px' }}
                    value={value.alt || ''}
                    onChange={e => handleImageChange(key, 'alt', e.target.value)}
                    placeholder="Alt text"
                  />
                </div>
              )
            }

            const isLong = typeof value === 'string' && value.length > 80

            return (
              <div key={key} style={styles.field}>
                <label style={styles.label}>
                  {fieldName}
                  <span style={styles.badge}>text</span>
                </label>
                {isLong ? (
                  <textarea
                    style={{ ...styles.input, minHeight: '80px', resize: 'vertical' }}
                    value={value || ''}
                    onChange={e => handleChange(key, e.target.value)}
                  />
                ) : (
                  <input
                    style={styles.input}
                    value={value || ''}
                    onChange={e => handleChange(key, e.target.value)}
                  />
                )}
              </div>
            )
          })}
        </div>
      ))}

      <div style={{ padding: '20px 32px', borderTop: '1px solid #eee', color: '#999', fontSize: '13px' }}>
        <a href="/" style={{ color: '#0070f3', textDecoration: 'none' }}>← Back to site</a>
        {' · '}
        Powered by Handoff CMS
      </div>
    </div>
  )
}

const styles: Record<string, React.CSSProperties> = {
  container: {
    maxWidth: '720px',
    margin: '0 auto',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    background: '#fff',
    minHeight: '100vh',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '24px 32px',
    borderBottom: '1px solid #eee',
    position: 'sticky',
    top: 0,
    background: '#fff',
    zIndex: 10,
  },
  title: {
    fontSize: '20px',
    fontWeight: 700,
    margin: 0,
  },
  subtitle: {
    fontSize: '13px',
    color: '#666',
    margin: '4px 0 0',
  },
  saveButton: {
    padding: '10px 24px',
    background: '#0070f3',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: '14px',
  },
  section: {
    padding: '24px 32px',
    borderBottom: '1px solid #f0f0f0',
  },
  sectionTitle: {
    fontSize: '14px',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    color: '#999',
    marginBottom: '16px',
  },
  field: {
    marginBottom: '16px',
  },
  label: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    fontWeight: 500,
    color: '#333',
    marginBottom: '6px',
  },
  badge: {
    fontSize: '10px',
    padding: '1px 6px',
    borderRadius: '4px',
    background: '#f0f0f0',
    color: '#888',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '14px',
    fontFamily: 'inherit',
    outline: 'none',
    boxSizing: 'border-box' as const,
    transition: 'border-color 0.15s',
  },
}
